export default {
    item0: {
        imgSrc: "./images/man/man1.jpg",
        name: "오버핏 리버서블 퍼 자켓 블랙",
        type: ["outer"],
        price: "159000",
        sale: "99000",
        iconContent: ["이벤트특가", "신상"],
        descMain: null,
        descSub: null,
    },
    item2: {
        imgSrc: "./images/man/man2.jpg",
        name: "커뮤터 스트레치 라이트 패딩 자켓 애쉬카키",
        type: ["outer"],
        price: "189000",
        sale: "119000",
        iconContent: ["이벤트특가", "~3XL", "신상"],
        descMain: null,
        descSub: null,
    },
    item3: {
        imgSrc: "./images/man/man3.jpg",
        name: "맨즈 리버서블 포켓 퀼티드 자켓 사파리카키",
        type: ["outer"],
        price: "139000",
        sale: "89000",
        iconContent: ["이벤트특가", "신상"],
        descMain: null,
        descSub: null,
    },
    item4: {
        imgSrc: "./images/man/man4.jpg",
        name: "텍스처드 플리스 집업 자켓 블랙",
        type: ["outer"],
        price: "99000",
        sale: "69000",
        iconContent: ["~2XL", "신상"],
        descMain: null,
        descSub: null,
    },
    item5: {
        imgSrc: "./images/man/man5.jpg",
        name: "커뮤터 스트레치 라이트 롱 패딩 블랙",
        type: ["outer"],
        price: "199000",
        sale: "169000",
        iconContent: ["~3XL", "신상"],
        descMain: "[맨즈] 경량 충전재로 모든 일상을 가볍고 따뜻하게!",
        descSub: null,
    },
    item6: {
        imgSrc: "./images/man/man6.gif",
        name: "리버서블 퀼팅 플리스 코트 블랙",
        type: ["outer"],
        price: "169000",
        sale: "119000",
        iconContent: ["이벤트특가", "~2XL", "신상"],
        descMain: null,
        descSub: null,
    },
    item7: {
        imgSrc: "./images/man/man7.jpg",
        name: "넥리스 심플 경량 패딩 다크그레이",
        type: ["outer"],
        price: "119000",
        sale: "99000",
        iconContent: ["~2XL", "신상"],
        descMain: "[맨즈] 가볍고 따뜻한 마이크로 볼 충전재 #품절주의",
        descSub: null,
    },
    item8: {
        imgSrc: "./images/man/man8.jpg",
        name: "플렉스 집업 후디",
        type: ["outer"],
        price: "72000",
        sale: "49000",
        iconContent: ["~2XL", "신상"],
        descMain: null,
        descSub: null,
    },
    item9: {
        imgSrc: "./images/man/man9.jpg",
        name: "유틸라이트 포텐셜 롱슬리브 블랙",
        type: ["top"],
        price: "49000",
        sale: "15000",
        iconContent: ["이벤트특가", "신상"],
        descMain: null,
        descSub: null,
    },
    item10: {
        imgSrc: "./images/man/man10.jpg",
        name: "프렌치 테리 하프집업 스웨트셔츠 네이비",
        type: ["top"],
        price: "82000",
        sale: "59000",
        iconContent: ["~2XL", "신상"],
        descMain: "편안한 루즈 핏 #셋업 스타일링",
        descSub: "윤성빈's PICK!",
    },
    item11: {
        imgSrc: "./images/man/man11.jpg",
        name: "스포츠 윈드 테크 롱슬리브 블랙",
        type: ["top"],
        price: "82000",
        sale: "59000",
        iconContent: ["~3XL", "신상"],
        descMain: null,
        descSub: null,
    },
    item12: {
        imgSrc: "./images/man/man12.jpg",
        name: "필드 하프집업 롱슬리브 1+1",
        type: ["top"],
        price: "98000",
        sale: "50000",
        iconContent: ["이벤트특가", "~2XL", "신상"],
        descMain: null,
        descSub: null,
    },
    item13: {
        imgSrc: "./images/man/man13.jpg",
        name: "트리플 엑스 숏슬리브 1+1",
        type: ["top"],
        price: "58000",
        sale: "44800",
        iconContent: ["~3XL", "신상"],
        descMain: null,
        descSub: "맨즈 상의 누적판매 1위 #윤성빈's PICK!",
    },
    item14: {
        imgSrc: "./images/man/man14.jpg",
        name: "하이쿨링 테크 숏슬리브 1+1",
        type: ["top"],
        price: "88000",
        sale: "49800",
        iconContent: ["~3XL", "신상"],
        descMain: null,
        descSub: "윤성빈's PICK!",
    },
    
};
